COLUMNS:

  age: int64 
  workclass: object
  fnlwgt: int64
  education: object 
  marital_status: object 
  occupation: object
  sex: object
  capital_gain: int64
  capital_loss: int64
  hours_per_week: int64
  country: object  

TARGET_COLUMN:

  name: salary