artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Milind-Shende/Practice-Dataset/raw/main/census.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/census.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/census.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model_file.model
  transformer_name: transformer.joblib
  target_name: target.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model_file.model
  transformer_path: artifacts/model_trainer/transformer.joblib
  target_path: artifacts/model_trainer/target.joblib
  metric_file_name_train: artifacts/model_evaluation/metrics_train.json
  metric_file_name_test: artifacts/model_evaluation/metrics_test.json